import { Role } from "../../common/enums/role.enum";

export const MEMBERSHIP_MESSAGES = {
  ONLY_JOB_SEEKERS_ALLOWED: "Only Job Seekers can subscribe to job seeker membership plans.",
  ONLY_RECRUITERS_ALLOWED: "Only Recruiters can subscribe to recruiter membership plans.",
  MEMBERSHIP_NOT_FOUND: "Membership plan not found or inactive.",
  ALREADY_SUBSCRIBED: "You are already subscribed to this plan.",
  SAME_PLAN_ACTIVE: "You are already subscribed to this plan.",
  HIGHER_PLAN_ACTIVE: "Cannot purchase a lower-level plan while your higher plan is currently active.",
  DOWNGRADE_NOT_ALLOWED: "Downgrading is not permitted during an active subscription period.",
  SUBSCRIPTION_SUCCESS: "Membership subscription activated successfully.",
  CANCEL_SUCCESS: "Subscription cancelled successfully.",
  NO_ACTIVE_SUBSCRIPTION: "You do not have an active subscription.",
  FETCH_SUCCESS: "Memberships fetched successfully.",
  CURRENT_SUBSCRIPTION_SUCCESS: "Current subscription fetched successfully.",
  HISTORY_SUCCESS: "Subscription history fetched successfully.",
  PRO_PLAN_REQUIRED: "Pro or Premium membership required to access this feature.",
  PREMIUM_PLAN_REQUIRED: "Premium membership required to access this feature.",
  PROFESSIONAL_RECRUITER_REQUIRED: "Professional or Enterprise Recruiter membership required.",
  ENTERPRISE_RECRUITER_REQUIRED: "Enterprise Recruiter membership required.",
  JOB_POST_LIMIT_EXCEEDED: "Upgrade your membership to create more jobs. Free plan is limited to 3 active jobs.",
};

export const PLAN_LEVELS: Record<string, Record<string, number>> = {
  [Role.JOB_SEEKER]: {
    Free: 1,
    Pro: 2,
    Premium: 3,
  },
  [Role.RECRUITER]: {
    Free: 1,
    Professional: 2,
    Enterprise: 3,
  },
};

export const DEFAULT_MEMBERSHIP_PLANS = [
  {
    name: "Free",
    role: Role.JOB_SEEKER,
    price: 0,
    currency: "INR",
    durationInDays: 30,
    description: "Essential job search tools to get you started",
    isPopular: false,
    isRecommended: false,
    isActive: true,
    features: [
      { title: "Unlimited profile creation", description: "Build a complete job seeker profile", enabled: true },
      { title: "Browse jobs", description: "Search & filter all public job listings", enabled: true },
      { title: "Upload resume", description: "Upload PDF or DOCX resumes", enabled: true },
      { title: "Apply up to 20 jobs/month", description: "Standard job application limit", enabled: true },
      { title: "Basic support", description: "Community & email support", enabled: true },
      { title: "Featured profile", description: "Highlight profile in search results", enabled: false },
      { title: "AI Resume Suggestions", description: "AI resume analysis & scoring", enabled: false },
      { title: "AI Cover Letter Generator", description: "Generate custom cover letters with AI", enabled: false },
    ],
  },
  {
    name: "Pro",
    role: Role.JOB_SEEKER,
    price: 299,
    currency: "INR",
    durationInDays: 30,
    description: "Accelerate your job search with AI tools and priority application",
    isPopular: true,
    isRecommended: true,
    isActive: true,
    features: [
      { title: "Unlimited job applications", description: "Apply to as many jobs as you want", enabled: true },
      { title: "Featured profile", description: "Highlight profile in recruiter searches", enabled: true },
      { title: "Priority in recruiter search", description: "Rank higher in candidate candidate search", enabled: true },
      { title: "AI Resume Suggestions", description: "Get smart recommendations to optimize your resume", enabled: true },
      { title: "AI Cover Letter Generator", description: "Generate targeted cover letters instantly", enabled: true },
      { title: "Early access to new jobs", description: "Apply to newly posted jobs 24 hours earlier", enabled: true },
      { title: "Profile analytics", description: "See who viewed your profile", enabled: true },
      { title: "Priority Support", description: "24/7 priority ticket support", enabled: true },
    ],
  },
  {
    name: "Premium",
    role: Role.JOB_SEEKER,
    price: 599,
    currency: "INR",
    durationInDays: 30,
    description: "Complete career transformation with 1-on-1 AI reviews & roadmap",
    isPopular: false,
    isRecommended: false,
    isActive: true,
    features: [
      { title: "Everything in Pro", description: "All Pro features included", enabled: true },
      { title: "Unlimited AI Resume Reviews", description: "Deep AI review & resume optimization", enabled: true },
      { title: "Unlimited AI Interview Practice", description: "Mock interview practice with AI feedback", enabled: true },
      { title: "Career Roadmap", description: "Personalized career growth path", enabled: true },
      { title: "Salary Insights", description: "Detailed market salary benchmarks", enabled: true },
      { title: "One Click Apply", description: "Instant application with saved profile", enabled: true },
      { title: "Unlimited Saved Jobs", description: "Save and organize jobs without limit", enabled: true },
      { title: "Personal Career Dashboard", description: "Advanced analytics & application tracking", enabled: true },
    ],
  },
];

export const DEFAULT_RECRUITER_MEMBERSHIP_PLANS = [
  {
    name: "Free",
    role: Role.RECRUITER,
    price: 0,
    currency: "INR",
    durationInDays: 30,
    description: "Essential features to get started with basic hiring",
    isPopular: false,
    isRecommended: false,
    isActive: true,
    features: [
      { title: "Create Company Profile", description: "Set up company details & logo", enabled: true },
      { title: "Post up to 3 Active Jobs", description: "Maximum 3 active job postings", enabled: true },
      { title: "View Applicants", description: "Review incoming candidate applications", enabled: true },
      { title: "Basic Dashboard", description: "Application tracking & status updates", enabled: true },
      { title: "Email Notifications", description: "Instant email alert on new applicant", enabled: true },
      { title: "Featured Job Listings", description: "Highlight jobs at top of search", enabled: false },
      { title: "Candidate Search & Filters", description: "Search candidate pool directly", enabled: false },
      { title: "Job Performance Analytics", description: "Views & click-through analytics", enabled: false },
    ],
  },
  {
    name: "Professional",
    role: Role.RECRUITER,
    price: 999,
    currency: "INR",
    durationInDays: 30,
    description: "Accelerate hiring with unlimited job posts and candidate search",
    isPopular: true,
    isRecommended: true,
    isActive: true,
    features: [
      { title: "Unlimited Job Posts", description: "Post as many active jobs as needed", enabled: true },
      { title: "Featured Job Listings", description: "Highlight jobs at top of candidate searches", enabled: true },
      { title: "Candidate Search", description: "Direct access to candidate profile database", enabled: true },
      { title: "Advanced Filters", description: "Filter candidates by skills, experience, location", enabled: true },
      { title: "Company Branding", description: "Custom company banner & media showcase", enabled: true },
      { title: "Job Performance Analytics", description: "Detailed views & application analytics", enabled: true },
      { title: "Priority Email Support", description: "Fast ticket resolution support", enabled: true },
      { title: "AI Candidate Matching", description: "Smart AI recommendations", enabled: false },
    ],
  },
  {
    name: "Enterprise",
    role: Role.RECRUITER,
    price: 2499,
    currency: "INR",
    durationInDays: 30,
    description: "Complete enterprise suite for high-volume hiring teams",
    isPopular: false,
    isRecommended: false,
    isActive: true,
    features: [
      { title: "Everything in Professional", description: "All Professional features included", enabled: true },
      { title: "Unlimited Recruiters & Team Members", description: "Add multiple recruiter sub-accounts", enabled: true },
      { title: "Multiple Company Admins", description: "Manage team permissions & roles", enabled: true },
      { title: "AI Candidate Matching", description: "AI scoring & matching for applications", enabled: true },
      { title: "Bulk Job Posting", description: "Import & post multiple jobs at once", enabled: true },
      { title: "Applicant Pipeline & Collaboration", description: "Team feedback & rating pipeline", enabled: true },
      { title: "API Access & Dedicated Support", description: "Custom API integrations & account manager", enabled: true },
      { title: "Talent Pool Management", description: "Save & organize talent pools", enabled: true },
    ],
  },
];
